baseURL = "https://koka.no"
languageCode = "nb-no"
title = "Kodekameratene"
theme = "kross-hugo"
summaryLength = "10"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"

# navigation
[menu]

  [[menu.main]]
  name = "Om oss"
  URL = "about"
  weight = 2

   [[menu.main]]
   name = "Blog"
   URL = "blog"
   weight = 3

 [[menu.main]]
   name = "Chat"
   URL = "https://discord.gg/Vc3A7EX"
   weight = 4

  # [[menu.main]]
  # name = "Portfolio"
  # URL = "portfolio"
  # weight = 4

  # [[menu.main]]
  # name = "Kontakt"
  # URL = "contact"
  # weight = 5

[params]
logo = "images/logo.png"
home = "Hjem"
# Meta data
author = "Kodekameratene"
description = "Kodekameratene**; et kode-kollektiv."
# Google Analitycs
googleAnalitycsID = "UA-141115558-1"

  # Preloader
  [params.preloader]
  enable = false

  [params.contact]
  enable = true
  formAction = "https://formspree.io/hei@koka.no" #contact form works with formspree.io

  [params.footer]
  email = "hei@koka.no"
  # phone = "+880 2544 658 256"
  address = "Stavanger & Trondheim"
